sudo: false
language: node_js
os: linux
cache:
  directories:
  - node_modules
before_install:
  - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
  - npm install -g greenkeeper-lockfile@1
  - npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run lint
  - npm test -- --coverage
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
  - npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: julien@frad.in
  api_key:
    secure: bUZI1O0BctfJmpVblUmS+tIbFXDhTIV4w5RZxQwrZqTXIt1+ZJvlppkA6naxpo5W+z9H9VLFKBcQ8QykJaa7Xfs2rEEyC3rcQ4NbmX+UwpDP018twK+KbLWWVjPDySOCjlT+KdSuYZi4esqYnvtJN06rZxMRqBL3SpP5j9iE8MN6fCtOO2wXXykjKjzwAyeeCVSUDAlDi0l0oQ0XOX/bRq/Hg+t2rAxi7DxVr3VQl5inWMAIS26phGCOg7BGIPjog4ez/JmKHe8dKTpdpuV9Yu74WcVHBLVSYV79SLn5zMHdSUz1WFsMNs0Dzj1hzy31SdQ5J8jSYtN/OPRUDvWI7Ru87LX+wu2Ry3pN9bCVkKWryJWmH+xQLgGFWKQ/vZTYSmRx4i9DJJJ2pml7140s2HAEmR68jsgeb8aSiaJV92HLYHj66QhHB8l9sQcDScIHVMhKyVo1/q+QlxjsvoDS64oxUokBpWaQacIXpr3ANUUu/kH1l4oXFrBJljNd0ROPyNcEdGnXKVF9rUVnZVZjk4tjDx/NCnQHstbyqqER2SfhDoXTfmfEHctwkvsp3WdmepF8K8FDFIi8U8urU6cgR/A0BqacS+LQ3pFVd7ZcBrmx/2f0tgK7TeKyjsdgiw4yhkmlmgtiQCIyTKYNApxkldB8+aSHiKwgPEkwMPcSUAg=
  on:
    tags: true
notifications:
  email: false
